package trddd;
// Generated Dec 22, 2015 2:46:22 PM by Hibernate Tools 4.3.1



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private int id;
     private String personName;

    public Person() {
    }

	
    public Person(int id) {
        this.id = id;
    }
    public Person(int id, String personName) {
       this.id = id;
       this.personName = personName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }




}


